# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - r: release
      os: linux
      env: R_CODECOV=true
    - r: release
      os: osx
    - r: oldrel
      os: linux
    - r: devel
      os: linux

addons:
  apt:
    packages:
      - libglpk-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
